<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAySEAd\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAySEAd/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPAySEAd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPAySEAd\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerPAySEAd\srcApp_KernelProdContainer([
    'container.build_hash' => 'PAySEAd',
    'container.build_id' => '8b795436',
    'container.build_time' => 1630501017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAySEAd');
