<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'http_client' shared service.

include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-client-contracts/HttpClientInterface.php';
include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-client/HttpClient.php';

$this->privates['http_client'] = $instance = \Symfony\Component\HttpClient\HttpClient::create([], 6);

$a = new \Symfony\Bridge\Monolog\Logger('http_client');
$a->pushProcessor(($this->privates['App\\Logger\\VarargsLogMessageProcessor'] ?? ($this->privates['App\\Logger\\VarargsLogMessageProcessor'] = new \App\Logger\VarargsLogMessageProcessor())));
$a->pushHandler(($this->privates['monolog.handler.console'] ?? $this->getMonolog_Handler_ConsoleService()));
$a->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));

$instance->setLogger($a);

return $instance;
