<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExternalJudgement extends \App\Entity\ExternalJudgement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'extjudgementid', 'externalid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'result', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'verified', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'jury_member', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'verify_comment', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'starttime', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'endtime', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'valid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'cid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'contest', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'submitid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'submission', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'external_runs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'extjudgementid', 'externalid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'result', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'verified', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'jury_member', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'verify_comment', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'starttime', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'endtime', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'valid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'cid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'contest', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'submitid', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'submission', '' . "\0" . 'App\\Entity\\ExternalJudgement' . "\0" . 'external_runs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExternalJudgement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getExtjudgementid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getExtjudgementid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtjudgementid', []);

        return parent::getExtjudgementid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalid($externalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalid', [$externalid]);

        return parent::setExternalid($externalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalid', []);

        return parent::getExternalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setResult($result)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResult', [$result]);

        return parent::setResult($result);
    }

    /**
     * {@inheritDoc}
     */
    public function getResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', []);

        return parent::getResult();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerified($verified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerified', [$verified]);

        return parent::setVerified($verified);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerified', []);

        return parent::getVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuryMember($juryMember)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuryMember', [$juryMember]);

        return parent::setJuryMember($juryMember);
    }

    /**
     * {@inheritDoc}
     */
    public function getJuryMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuryMember', []);

        return parent::getJuryMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifyComment($verifyComment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifyComment', [$verifyComment]);

        return parent::setVerifyComment($verifyComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifyComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifyComment', []);

        return parent::getVerifyComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setStarttime($starttime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStarttime', [$starttime]);

        return parent::setStarttime($starttime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStarttime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStarttime', []);

        return parent::getStarttime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndtime($endtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndtime', [$endtime]);

        return parent::setEndtime($endtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndtime', []);

        return parent::getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', [$valid]);

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', []);

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCid(int $cid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCid', [$cid]);

        return parent::setCid($cid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCid', []);

        return parent::getCid();
    }

    /**
     * {@inheritDoc}
     */
    public function setContest(\App\Entity\Contest $contest = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContest', [$contest]);

        return parent::setContest($contest);
    }

    /**
     * {@inheritDoc}
     */
    public function getContest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContest', []);

        return parent::getContest();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmitid(int $submitid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmitid', [$submitid]);

        return parent::setSubmitid($submitid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmitid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmitid', []);

        return parent::getSubmitid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmission(\App\Entity\Submission $submission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmission', [$submission]);

        return parent::setSubmission($submission);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmission', []);

        return parent::getSubmission();
    }

    /**
     * {@inheritDoc}
     */
    public function addExternalRun(\App\Entity\ExternalRun $externalRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExternalRun', [$externalRun]);

        return parent::addExternalRun($externalRun);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExternalRun(\App\Entity\ExternalRun $externalRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExternalRun', [$externalRun]);

        return parent::removeExternalRun($externalRun);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalRuns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalRuns', []);

        return parent::getExternalRuns();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxRuntime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxRuntime', []);

        return parent::getMaxRuntime();
    }

    /**
     * {@inheritDoc}
     */
    public function getSumRuntime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSumRuntime', []);

        return parent::getSumRuntime();
    }

}
